import { AlertCircle } from "lucide-react";

export default function Disclaimer() {
  return (
    <section className="py-12 bg-slate-50 border-b border-slate-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-12">
        <div className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-sm flex flex-col sm:flex-row items-center gap-4 text-center sm:text-left">
          <AlertCircle className="w-8 h-8 text-amber-600 flex-shrink-0 animate-pulse duration-[3000ms]" />
          <p className="text-xs sm:text-sm text-slate-650 leading-relaxed">
            <span className="font-extrabold text-slate-900 uppercase tracking-widest mr-2">Core Disclaimer:</span> 
            HealthPredict is for informational purposes only and does NOT constitute a clinical diagnosis or medical assessment. 
            All risk evaluation classifications are generated by statistical modeling and cannot replace certified medical diagnostics, clinical ultrasounds, or metabolic panels. 
            Always consult a licensed healthcare professional or Gynaecologist for official diagnosis, prescriptive therapy, and tailored treatment designs.
          </p>
        </div>
      </div>
    </section>
  );
}
